version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: migrato.mysql
    ports:
    - "3335:3306"
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
    - network-migrato

networks:
  network-migrato: